# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Eddy's Notebook"
description: > # this means to ignore newlines until "baseurl:"
  My ideas about stuff. Inspired by a similar notebook maintained by my
  statistics professor (http://bactra.org/notebooks/)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://eddyyeo.com" # the base hostname & protocol for your site
github_username:  yeoedward

# Build settings
markdown: kramdown
